version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/news
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  #nginx:
    #image: nginx:alpine
    #container_name: nginx
   # volumes:
    #  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #ports:
    #  - "80:80"
   # depends_on:
   #   - nextjs-app
   # networks:
    #  - app_network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=news
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
